### ISSUE TITLE
ARM11 data abort on loading menu

### ISSUE THREAD

**Issue by Anonymous941** [matbo87/snes9x_3ds#2]
This is a test on [abb7daa](https://github.com/matbo87/snes9x_3ds/commit/abb7daabf0a65f33e81d3956762d5a759f6dae72), hand-compiled by me and ran on my O2DS with Luma CFW.

Chrono Trigger and EarthBound boot, and sound and controls work.  On the bottom screen, "Failed to load image sdmc:/.../game.png" is visible.

The reason that I didn't test these games beyond the title screen is because when I tap on the bottom screen to enter the menu, I get an ARM11 data abort.  I've tried a few times on both games, and this happens with both games.  [Here is the crash dump.](https://github.com/matbo87/snes9x_3ds/files/12208160/crash_dump_00000004.dmp.txt)

This doesn't happen when I run the original bubble2k16 or Xeddius-Network (the one I'm currently using until this works) fork.

Also, thanks for making this fork!  I'm excited to have better SNES emulation on my O2DS. :)

**Comment by matbo87** [comment]
I'm late, i know :)
I wasn't able to reproduce these crashes. Let me know, if this is still happening with the latest release (v1.50).

**Comment by Anonymous941** [comment]
> I'm late, i know :)
No worries!  The other fork works in the meantime.
> I wasn't able to reproduce these crashes. Let me know, if this is still happening with the latest release (v1.50).
Unfortunately yes, it's still happening, even when I rename `3ds/snes9x_3ds` and the other SNES9x configuration files I could find: [crash_dump_00000007.dmp.txt](https://github.com/matbo87/snes9x_3ds/files/12569984/crash_dump_00000007.dmp.txt).  Maybe it has something to do with my being an Old 2DS?

**Comment by matbo87** [comment]
Yes, O2DS (and O3DS) might behave differently. I can only test on New2ds and new3ds here, so it makes it more difficult for me, to debug the actual problem. When you tap on the bottom screen the emulator saves the SRAM if necessary.
You can try one of the following:
- Uncomment [this line](https://github.com/matbo87/snes9x_3ds/blob/ff0bc22a72ca6e4e3271885f9eb786b1bc8bc12c/source/3dsimpl.cpp#L659C5-L659C5) for testing.
- if you haven't tried it already: hand-compile the Xeddius-Network version (v1.45) and check if the emulator doesn't crash. If its also crashing, it's probably due to newer libctru version I guess?
- if hand-compiled v1.45 works, try tag v1.46. Look for any old snes9x ".cfg" files which can cause issues.
Keep in mind that tags from v1.46 to v1.49 are probably unstable and may also lead to crashes. But at least it can help to kind of isolate the problem.

**Comment by Anonymous941** [comment]
> Uncomment [this line](https://github.com/matbo87/snes9x_3ds/blob/ff0bc22a72ca6e4e3271885f9eb786b1bc8bc12c/source/3dsimpl.cpp#L659C5-L659C5) for testing.

This worked, the culprit is line 991:

```cpp
Memory.SaveSRAM (path.c_str());
```

Auto saving SRAM with either line commented out was working regardless.

> if you haven't tried it already: hand-compile the Xeddius-Network version (v1.45) and check if the emulator doesn't crash. If its also crashing, it's probably due to newer libctru version I guess?

Still want me to do this?

**Comment by matbo87** [comment]
if you comment out `Memory.SaveSRAM (path.c_str());` no srm file should be created in `saves` directory as far as i know. Or did you mix it up with the "Automatically save state on exit..." option?

If line 991 caused the crash, it might be an invalid pointer. I'm still not sure, why this is no issue at all on my devices.
Maybe file3dsGetAssociatedFilename(...) causes it. I will have a look at it.

You don't need to hand-compile the other version. But you could execute other saving-tasks like screenshot, applying cheats, save states, etc. - all these tasks make use of file3dsAssociatedFilename()

**Comment by Anonymous941** [comment]
> if you comment out `Memory.SaveSRAM (path.c_str());` no srm file should be created in `saves` directory as far as i know. Or did you mix it up with the "Automatically save state on exit..." option?

What I meant is that in `S9xAutoSaveSRAM`, commenting out `Memory.SaveSRAM (path.c_str());` stopped the segmentation fault from happening

> You don't need to hand-compile the other version. But you could execute other saving-tasks like screenshot, applying cheats, save states, etc. - all these tasks make use of file3dsAssociatedFilename()

I've tried save states, and nothing I did caused the segmentation fault.  Commenting out that line seemed to make this work, although obviously without save data

**Comment by matbo87** [comment]
I've pushed some changes on a bugfixing branch. This may solve the crashes on your O2DS.
best case: [02788b](https://github.com/matbo87/snes9x_3ds/commit/02788b17d038e30e612dcbf0719ec45a8fc54a43) already works for you. If it doesn't crash, please also check, if the game related SRAM file has been created. 
If it still crashes or no SRAM file has been created, you can try [0e822f](https://github.com/matbo87/snes9x_3ds/commit/0e822f5eda8ee35415738f74dd4d5f203fce8022).
Looking forward to your feedback.

**Comment by Anonymous941** [comment]
[02788b](https://github.com/matbo87/snes9x_3ds/commit/02788b17d038e30e612dcbf0719ec45a8fc54a43) works, and the SRM file has been created.  Thanks for your help!

**Comment by Anonymous941** [comment]
Let me know if you want further testing to narrow down the error, I'd be happy to help

**Comment by matbo87** [comment]
> Let me know if you want further testing to narrow down the error, I'd be happy to help

I'll appreciate it. Just let me know if you find any other bugs.
Current fix is already part of  [nightly build](https://github.com/matbo87/snes9x_3ds/suites/16251846391/artifacts/928053078) and will be included in upcoming release.
