### ISSUE TITLE
Mega Man X -- Upgrades don't save

### ISSUE THREAD

**Issue by taylorfry** [matbo87/snes9x_3ds#26]
Mega Man X has capsules that give upgrades throughout levels. After collecting one of the upgrades and either dying or completing the level, the upgrade doesn't stay like it should. Dying to a boss should place you in the room before the boss room, but it sends you to the beginning of the level. I read this may be a bad ROM or a piracy deterrent, but trying to recreate the issues with the same ROM on the PC version of SNES9x provides no problems at all.

**Comment by Anonymous941** [comment]
What's the hash of the ROM?

**Comment by taylorfry** [comment]
This is what I get using https://www.romhacking.net/hash/ 

Database match: Mega Man X (USA) (Rev 1)
Database: No-Intro: Super Nintendo Entertainment System (v. 20210222-050638)
File/ROM SHA-1: C65216760BA99178100A10D98457CF11496C2097
File/ROM CRC32: DED53C64

**Comment by Anonymous941** [comment]
That's definitely a clean ROM, so the emulator must be the issue

**Comment by matbo87** [comment]
@taylorfry 
The emulator is based on the snes9x 1.43 core (snes9x2005). The reason why bubble2k chose this rather old core is most likely better performance at the cost of poorer accuracy/compatibility.
I would guess that older snes9x versions don't handle these anti-piracy things like in Mega Man X very well. Can you share the savegame so i can easily reproduce the issue? You can also try retroarch with the same core to check if it's really a core issue or if some of the core changes in bubble2k's code cause this behavior.

**Comment by taylorfry** [comment]
The Mega Man games use passwords instead of save files so I've attached a couple save states. The first one is at the level select screen and the second is right after getting the leg upgrade.
[Mega Man X save states.zip](https://github.com/user-attachments/files/17180749/Mega.Man.X.save.states.zip)

**Comment by matbo87** [comment]
@taylorfry Thanks for the save state. I was able to reproduce the leg upgrade issue. There is a new build which you can find [here](https://github.com/matbo87/snes9x_3ds/actions/runs/11307072377/artifacts/2048829087). The upgrade should now remain after dying.
Is _"Dying to a boss should place you in the room before the boss room"_ also solved with this new build? I'm not very familiar with this game and didn't really have the patience to continue the level until the boss fight. If this bug still persists, another save state may help :)

**Comment by taylorfry** [comment]
Thank you so much! I tested it out by dying and completing the level and the upgrade stays in both scenarios. I really appreciate the fix. Is there anyway I can help support the work you've done?

**Comment by matbo87** [comment]
@taylorfry Nice to hear that it works. 

Reporting errors with clear reproduction steps, as you have done, is already very supportive. Just keep in mind that I probably won't be able to solve a game-related bug every time. My programming skills are limited in this respect :) In this specific case it was relatively easy as it was a regression and still worked in version 1.30.
