### ISSUE TITLE
RetroArch Citra core not working with SNES9X Fork

### ISSUE THREAD

**Issue by Wave3prime15** [matbo87/snes9x_3ds#27]
When i start a game it gives a black screen (im not using 2018 version)

https://github.com/user-attachments/assets/b1649c4a-ced5-4c2b-b7cc-c9be866afa0d

**Comment by matbo87** [comment]
The w component needs to be set to 1.0 in `shaderslow.v` and `shaderfast2.g` to get rid of the black screen on citra. It still works fine on real 3DS without these adjustments, so i will close this issue. 
I noticed  that you created similar issues for other emulators where you already got the solution for your problem: 

> using a native emulator if you are already using a PC

**Comment by Wave3prime15** [comment]
ok but where is shadowslow.v and shaderfast2.g on retroarch citra or is it in the snes9x emulator?
