### ISSUE TITLE
Dark mode | Default starting folder | B button for going up one directory

### ISSUE THREAD

**Issue by InsanePrimate** [matbo87/snes9x_3ds#4]
Please make it possible to use the B button (or any button, really) to go up one directory. I have my ROMs organized in folders by genre (RPG, Jump & Run, Shoot 'em Up, etc.) and having to scroll up to get to the ".. (Up to Parent Directory)" to change folders is somewhat tedious. Going up a directory by pressing B would be much nicer. Also, would it be possible to define a default starting folder? Just a suggestion, though. Thank you so much for improving this nice emulator!

Edit: While playing in the dark last night, I found myself wishing for a dark mode for the menu. XD

**Comment by matbo87** [comment]
@InsanePrimate 
Since I liked each of your 3 suggestions, I decided to implement them all.
Available in [latest nightly build](https://github.com/matbo87/snes9x_3ds/actions/runs/6392176098) and in upcoming version 1.51

**Comment by InsanePrimate** [comment]
Cool, thank you ill try them out!

**Comment by Anonymous941** [comment]
Thank you for adding these!
